services:
  web:
    build: ./docker/
    container_name: bithub-communicate-web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_DEBUG=1